### PR TITLE
Reintroduce CLOSE_QUERY_METHOD to Tab -kb

### LINKED ISSUE #392: Tab View - "x" to close tab not working
@kbiesbrock 
Getting error when "x" is clicked to close tab.
See image below:

Image

### PR DESCRIPTION
**Pull request by kbiesbrock**
Resolves #392

### CODE REVIEW

File: packages/azos-ui/vcl/tabs/tab.js [hunk 1]
```diff
@@ -36,7 +40,7 @@ export class Tab extends Block {
   #isAbsent = false;
   get isAbsent() { return this.#isAbsent; }
   set isAbsent(v) {
```
[the remark this answers is not in the document]
Comment (g8biesbrock) [reply packages/azos-ui/vcl/tabs/tab.js:42]: This code unselects a tab (if allowed) that is being set to `isAbsent = true`. An alternative would be to add it to `updated(changedProperties){ }` but the tab could be set to isAbsent before the unselection which could pose a timing issue while an active tab isAbsent.

File: packages/azos-ui/vcl/tabs/tab.js
Comment (g8biesbrock) [inline packages/azos-ui/vcl/tabs/tab.js:1]: After that conversation, I implemented the updated method listening for all the changes. As I was reviewing my changes, I observed (right below my new method), this requestUpdate override:
```javascript
  updated(changedProperties) {
    if ("isDisabled" in changedProperties ||
      "isEnabled" in changedProperties ||
      "isNa" in changedProperties ||
      "isApplicable" in changedProperties ||
      "isHidden" in changedProperties ||
      "isVisible" in changedProperties ||
      "isAbsent" in changedProperties ||
      "isReadonly" in changedProperties) {
      this.tabView.requestUpdate();
    }
  }

  requestUpdate(...args) {
    super.requestUpdate.call(this, ...args);
    if (this.tabView?.requestUpdate) this.tabView.requestUpdate();
  }
```

Methinks this `requestUpdate` nullifies the argument. Anytime `requestUpdate` is called on a `Tab`, it will automatically call `this.tabView?.requestUpdate.?()` .

So, I vote we remove remove updated and go with it as-is!

Comment (itadapter) [reply packages/azos-ui/vcl/tabs/tab.js:1]: ok. just commit your changes so we can close it
